[package]
name = "ldr_tools_py"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.20.3", features = ["extension-module"] }
numpy = "0.20.0"
ldr_tools = { path = "../ldr_tools" }

[build-dependencies]
pyo3-build-config = "0.20.3"

[lib]
name = "ldr_tools_py"
crate-type = ["cdylib"]
