[package]
name = "ldr_tools_py"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.24.1", features = ["extension-module", "py-clone"] }
numpy = "0.24.0"
ldr_tools = { path = "../ldr_tools" }
log = "0.4"

[build-dependencies]
pyo3-build-config = "0.24.1"

[lib]
name = "ldr_tools_py"
crate-type = ["cdylib"]
