name: Compile Release

on: 
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Build
      run: cargo build
    - name: Create Release Zip
      run: |
        cp target/debug/libldr_tools_py.so ldr_tools_blender/ldr_tools_py.so
        zip ldr_tools_blender ldr_tools_blender
    - uses: actions/upload-artifact@v3
      with:
        name: ldr_tools_blender_linux_x64
        path: ldr_tools_blender_linux_x64.zip
